// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNhwWgnCiLftoBDzBGAnQNqpDpbOv4IJc',
    appId: '1:203683450958:web:84bbfefb522a946f82331f',
    messagingSenderId: '203683450958',
    projectId: 'lab3-4e826',
    authDomain: 'lab3-4e826.firebaseapp.com',
    storageBucket: 'lab3-4e826.firebasestorage.app',
    measurementId: 'G-75038XE0NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3NGUN7Mo9jdWe4BcFLb_olq-acF5lq3Q',
    appId: '1:203683450958:android:23a12a8f3682415382331f',
    messagingSenderId: '203683450958',
    projectId: 'lab3-4e826',
    storageBucket: 'lab3-4e826.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGCSNpj93Ah8ZIrfiHK1Kx8tBMfKdKykE',
    appId: '1:203683450958:ios:06100ddbf40b024482331f',
    messagingSenderId: '203683450958',
    projectId: 'lab3-4e826',
    storageBucket: 'lab3-4e826.firebasestorage.app',
    iosBundleId: 'com.example.recipesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGCSNpj93Ah8ZIrfiHK1Kx8tBMfKdKykE',
    appId: '1:203683450958:ios:06100ddbf40b024482331f',
    messagingSenderId: '203683450958',
    projectId: 'lab3-4e826',
    storageBucket: 'lab3-4e826.firebasestorage.app',
    iosBundleId: 'com.example.recipesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNhwWgnCiLftoBDzBGAnQNqpDpbOv4IJc',
    appId: '1:203683450958:web:7593c464826d260e82331f',
    messagingSenderId: '203683450958',
    projectId: 'lab3-4e826',
    authDomain: 'lab3-4e826.firebaseapp.com',
    storageBucket: 'lab3-4e826.firebasestorage.app',
    measurementId: 'G-JRSNQH7ZCV',
  );
}
